FROM wazuh/wazuh-manager:4.8.0
EXPOSE 1514/tcp 1515/tcp 1516/tcp 514/udp 55000/tcp

ENV WAZUH_TEST_REPO=https://github.com/alexchristy/WazuhTest.git

WORKDIR /root

COPY init.sh /root/init.sh

# Install dependencies
RUN yum install git iproute golang -y

# Install WazuhTest tool
RUN git clone $WAZUH_TEST_REPO wazuh_test
WORKDIR /root/wazuh_test
RUN go build .
RUN chmod 751 WazuhTest
RUN cp ./WazuhTest /usr/bin

ENTRYPOINT ["/bin/sh", "/root/init.sh", "-i"]