FROM wazuh/wazuh-manager:4.8.0

ENV WAZUH_TEST_REPO=https://github.com/alexchristy/WazuhTest.git

WORKDIR /root

COPY init.sh /root/init.sh

# Install dependencies
RUN yum install git iproute golang -y 

# Install WazuhTest tool
RUN git clone $WAZUH_TEST_REPO wazuh_test
WORKDIR /root/wazuh_test
RUN go build .
RUN chmod 751 WazuhTest
RUN cp ./WazuhTest /usr/bin

ENTRYPOINT ["/bin/sh", "/root/init.sh"]