name: Wazuh Decoder & Rule CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  run-wazuh-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_IMAGE }}

    - name: Run container with branch info
      run: |
        docker run -e BRANCH_NAME=${GITHUB_REF_NAME} ${{ secrets.DOCKER_IMAGE }} || exit 1

    - name: Verify container exit status
      run: |
        echo "Container ran successfully."